# Generated by Django 5.1.1 on 2024-10-03 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(default=None, max_length=150, verbose_name="имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        default=None, max_length=150, verbose_name="фамилия"
                    ),
                ),
                (
                    "pantronymic",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="отчество"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default=None, max_length=254, unique=True, verbose_name="почта"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="дата создания рассылки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("однократно", "однократно"),
                            ("ежедневно", "ежедневно"),
                            ("еженедельно", "еженедельно"),
                            ("ежемесячно", "ежемесячно"),
                        ],
                        default="однократно",
                        max_length=30,
                        verbose_name="периодичность рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complited", "complited"),
                            ("created", "created"),
                            ("active", "active"),
                        ],
                        default="created",
                        max_length=30,
                        verbose_name="статус",
                    ),
                ),
                (
                    "next_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="дата и время следующей отправки отправки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ("id",),
                "permissions": [("can_edit_status", "can_edit_status")],
            },
        ),
        migrations.CreateModel(
            name="Mailing_attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_attempt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="fail", max_length=30, verbose_name="статус попытки"
                    ),
                ),
                (
                    "smtp_service_report",
                    models.TextField(
                        blank=True, null=True, verbose_name="ответ почтового сервиса"
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка",
                "verbose_name_plural": "попытки",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Тема сообщения"),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ("id",),
            },
        ),
    ]
