# Generated by Django 5.1.1 on 2024-10-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_alter_client_owner_alter_mailing_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(related_name='clients', to='mailings.client', verbose_name='клиенты'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='next_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время следующей отправки отправки'),
        ),
        migrations.AlterField(
            model_name='mailing_attempt',
            name='status',
            field=models.CharField(default='fail', max_length=30, verbose_name='статус попытки'),
        ),
    ]
